### ISSUE TITLE
Mermaid not rendering

### ISSUE THREAD

**Issue by nestanyol** [nestanyol/CoolBeans#23]
@lwjohnst86 the mermaid stopped rendering in my rstudio. Any guess why? It did before, so probably rstudio versions / update...?

**Comment by lwjohnst86** [comment]
Unfortunately, RStudio's version of Mermaid is VERY old. I would suggest using the Live Editor instead: https://mermaid.live/ Why Quarto doesn't render it though... I don't know....

**Comment by nestanyol** [comment]
Okay, yes! I used the Live Editor already. Maybe I just keep it as an image then, but others will not be able do make any modifications.
